services:
  - type: web
    name: swarmy
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: GROQ_API_KEY
        sync: false
      - key: CHROMA_PERSIST_DIR
        value: ./chroma_data
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: SMTP_USER
        sync: false
      - key: SMTP_APP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
